spring.application.name=BootMVCPROJ08-MiniProject-ErrorHandling

# JSP View Resolver
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

#Db releated 
spring.datasource.url=jdbc:mysql://localhost:3306/rgt
spring.datasource.username=root
spring.datasource.password=Manager
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#jpa to auto ceate based on entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 

server.port=8081
#for lazy intialization
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

server.error.whitelabel.enabled=true
